version: '3'
services:
  mc:
    build: ./mc
    container_name: mc
    hostname: mc
    environment:
      - WORKDIR /opt/minecraft
#    depends_on:
#      - mc_db
    ports:
    - "25565:25565"
    volumes:
    - D:/docker/mc/data:/opt/minecraft/data
    links:
    - mc_db
  mc_pannel:
    image: openjdk:8-alpine
    ports:
    - "80:80"
  mc_db:
    image: mysql:5.7
    container_name: mc_db
    hostname: mc_db
    restart: always
    environment:
      MYSQL_DATABASE: 'mc_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: 
    - '3306:3306'
    expose:
    - '3306'
    volumes:
    - D:/docker/mc/db:/var/lib/mysql